name: Release iam-role-aws-load-balancer-controller

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - "iam-role-aws-load-balancer-controller/**"

jobs:
  call-main:
    uses: ./.github/workflows/main.yaml
    with:
      path: iam-role-aws-load-balancer-controller
